;;; modules.el --- MyDE module system -*- coding: utf-8; no-byte-compile: t; lexical-binding: t; -*-

;; Copyright (C) 2020-2026  Allen Gooch

;; Author:   Allen Gooch <allen.gooch@gmail.com>
;; URL:      https://github.com/mojochao/myde.emacs
;; Keywords: convenience, configuration
;; Package-Requires: ((emacs "30.1"))

;; This file is not part of GNU Emacs.

;; Released under the MIT License; see the LICENSE file at the repository
;; root for the full text.

;;; Commentary:
;;
;; All machinery for the MyDE declarative module system lives here.
;;
;; A module is a directory `modules/<category>-<name>/' containing two
;; files (see AGENTS.md for the full convention):
;;
;;   lib.el  --  pure definitions, provides `myde-<category>-<name>'.
;;   cfg.el  --  side effects,    provides `myde-<category>-<name>-cfg'.
;;
;; This file exposes:
;;
;;   `myde-module'           --  cl-defstruct describing one module.
;;   `myde/m'                --  one-line constructor for descriptors.
;;   `myde-customize'        --  macro: emit `defcustom' toggles from
;;                               a list of descriptors.
;;   `myde-initialize'       --  function: walk a list of descriptors
;;                               and load each enabled module in order.
;;   `myde-load-module'      --  loader for a single module by name.
;;   `myde-module-category-enabled-p'
;;                           --  helper: does any sibling module in
;;                               the given category have its toggle on?
;;
;; Loading rules implemented by `myde-load-module':
;;
;;   core-*    Always loaded (no toggle generated).
;;   *-base    Loaded automatically iff any sibling in the same category
;;             is enabled (no toggle generated).
;;   others    Loaded iff `myde-module-<name>-enabled' is non-nil.
;;
;; The toggle defcustoms generated by `myde-customize' default to
;; `nil'.  Users opt modules in via `M-x customize-group RET myde-modules'
;; or by setting variables in `custom.el'.

;;; Code:

(require 'cl-lib)

;;;; Customization groups

(defgroup myde nil
  "MyDE Emacs configuration."
  :prefix "myde-")

(defgroup myde-modules nil
  "Toggle individual MyDE modules on or off.
Core modules (core-*) and base modules (*-base) are not listed here;
they are controlled automatically."
  :group 'myde
  :prefix "myde-module-")

;;;; Descriptor type

(cl-defstruct (myde-module (:constructor myde-module-create)
                           (:copier nil))
  "Descriptor for one MyDE module.

NAME is the directory basename under modules/, e.g. \"prog-elixir\".
The substring before the first `-' is the category (\"prog\"); the
remainder is the sub-category (\"elixir\").

DESCRIPTION is a short human-readable string used as the docstring of
the generated `myde-module-<name>-enabled' defcustom."
  (name        nil :read-only t :type string)
  (description ""  :read-only t :type string))

(defsubst myde/m (name description)
  "Build a `myde-module' descriptor from NAME and DESCRIPTION."
  (myde-module-create :name name :description description))

;;;; Descriptor classification helpers

(defsubst myde-module--core-p (m)
  "Return non-nil if module descriptor M is a `core-*' module."
  (string-prefix-p "core-" (myde-module-name m)))

(defsubst myde-module--base-p (m)
  "Return non-nil if M is a non-core `*-base' module."
  (let ((n (myde-module-name m)))
    (and (not (string-prefix-p "core-" n))
         (string-suffix-p "-base" n))))

(defsubst myde-module--toggleable-p (m)
  "Return non-nil if M should get a generated `defcustom' toggle."
  (not (or (myde-module--core-p m) (myde-module--base-p m))))

;;;; Loader

(defun myde-module-category-enabled-p (category)
  "Return non-nil if any non-base module in CATEGORY has its toggle on.
Used to auto-load `*-base' modules when at least one sibling is enabled."
  (let ((prefix (concat "myde-module-" category "-"))
        (result nil))
    (mapatoms
     (lambda (sym)
       (when (and (boundp sym)
                  (string-prefix-p prefix (symbol-name sym))
                  (string-suffix-p "-enabled" (symbol-name sym))
                  (symbol-value sym))
         (setq result t))))
    result))

(defun myde-load-module (name)
  "Load module NAME (e.g. \"prog-elixir\"), if not already loaded.

Idempotent: re-evaluating callers will not re-run module side effects.

Loading rules:
- `core-*' modules are always loaded.
- `*-base' modules (non-core) are loaded iff any sibling in the same
  category has its enable variable non-nil.
- All other modules are loaded iff their `myde-module-NAME-enabled'
  variable is non-nil."
  (let* ((feature     (intern (concat "myde-" name "-cfg")))
         (core-p      (string-prefix-p "core-" name))
         (base-p      (and (not core-p) (string-suffix-p "-base" name)))
         (enabled-var (intern (concat "myde-module-" name "-enabled")))
         (enabled-p   (cond
                       (core-p t)
                       (base-p (myde-module-category-enabled-p
                                (car (split-string name "-"))))
                       (t (and (boundp enabled-var)
                               (symbol-value enabled-var))))))
    (when (and enabled-p (not (featurep feature)))
      (load-file (expand-file-name (concat "modules/" name "/cfg.el")
                                   user-emacs-directory)))))

;;;; Public API: initialize + load

(defmacro myde-customize (modules)
  "Emit a `defcustom' toggle for every toggleable descriptor in MODULES.

MODULES is a form evaluated at macroexpansion time (typically the name
of a `defconst' bound earlier in the same file, or an inline `list'
form).  For each descriptor that is neither `core-*' nor `*-base', the
macro emits:

  (defcustom myde-module-<name>-enabled nil
    \"<DESCRIPTION>\"
    :type \\='boolean
    :group \\='myde-modules)

`core-*' and `*-base' modules are intentionally skipped: they have no
toggle.  Defaults are `nil' so users opt modules in explicitly."
  (let ((ms (eval modules lexical-binding))
        (forms nil))
    (dolist (m ms)
      (when (myde-module--toggleable-p m)
        (let* ((name (myde-module-name m))
               (desc (myde-module-description m))
               (var  (intern (concat "myde-module-" name "-enabled")))
               (doc desc))
          (push `(defcustom ,var nil ,doc
                   :type 'boolean
                   :group 'myde-modules)
                forms))))
    `(progn ,@(nreverse forms))))

(defun myde-initialize (modules)
  "Load each module in MODULES (a list of `myde-module' descriptors).
Order is preserved.  Idempotent."
  (dolist (m modules)
    (myde-load-module (myde-module-name m))))

(provide 'myde-modules)
;;; modules.el ends here
